name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour vers la dernière version de l'action checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v3  # Mise à jour vers la dernière version de l'action setup-python
        with:
          python-version: '3.8'

      - name: Cache pip packages
        uses: actions/cache@v3  # Mise à jour vers la dernière version de l'action cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances à partir de requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests  # Remplacez cette ligne par votre propre commande de tests
        id: unittest

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install security tools
        run: |
          pip install bandit safety pyraider

      - name: Run Bandit
        id: bandit
        run: bandit -r . || true

      - name: Run Safety
        id: safety
        run: safety check --full-report || true

      - name: Run Pyraider
        id: pyraider
        run: pyraider scan --path . --output-format json --output-file pyraider_report.json || true
