name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utilisation de la dernière version de l'action checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v3  # Utilisation de la dernière version de l'action setup-python
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask bandit safety pyraider  # Installe Flask et les outils de sécurité nécessaires

      - name: Run tests
        run: python -m unittest discover -s tests  # Exécution des tests (assurez-vous que le dossier "tests" existe)
        id: unittest

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install security tools
        run: |
          pip install bandit safety pyraider  # Installe les outils de sécurité nécessaires

      - name: Run Bandit
        id: bandit
        run: bandit -r . || true  # Analyse de sécurité avec Bandit (ignore les erreurs si elles surviennent)

      - name: Run Safety
        id: safety
        run: safety check --full-report || true  # Vérification de sécurité avec Safety (ignore les erreurs si elles surviennent)

      - name: Run Pyraider
        id: pyraider
        run: pyraider scan --path . --output-format json --output-file pyraider_report.json || true  # Scan de sécurité avec Pyraider
